{{- if .Values.secrets.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "beyondcloud.fullname" . }}-secrets
  labels:
    {{- include "beyondcloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  database-url: {{ include "beyondcloud.databaseUrl" . | quote }}
{{- end }}
